# Generated by Django 4.2.11 on 2024-04-24 08:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tag_trip_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
