# Generated by Django 4.2.11 on 2024-04-28 06:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_place_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='time_intend',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
