# Generated by Django 4.2.11 on 2024-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_time_intend_alter_trip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time_intend',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
