# Generated by Django 4.2.11 on 2024-04-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_time_intend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'trip')},
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('title', 'post')},
        ),
        migrations.AddField(
            model_name='place',
            name='open_time',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='trips/%Y/%m'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='trips.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='view',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='place',
            name='active',
        ),
        migrations.RemoveField(
            model_name='place',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='place',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated_date',
        ),
    ]
