# Generated by Django 4.2.11 on 2024-05-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_place_created_date_place_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
