# Generated by Django 4.2.13 on 2024-05-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='trips.post'),
        ),
    ]
