# Generated by Django 4.2.13 on 2024-05-29 02:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_rating_active_alter_rating_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
        ),
    ]
