# Generated by Django 4.2.13 on 2024-05-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_trip_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trip_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='trip', to='trips.trip'),
        ),
    ]
