# Generated by Django 4.2.13 on 2024-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_remove_trip_time_intend_trip_time_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
