# Generated by Django 4.2.13 on 2024-05-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_rating_updated_date_report_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
