# Generated by Django 4.2.13 on 2024-05-30 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_comment_created_date_comment_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
