# Generated by Django 4.2.13 on 2024-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_user_trip_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time_finish',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time_start',
            field=models.DateField(default=None),
        ),
    ]
